name: hookahorder_mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

  # Network
  dio: ^5.1.1
  retrofit: ^4.0.1

  # State & Storage
  get: ^4.6.5
  get_storage: ^2.1.1

  # etc
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  mask_text_input_formatter: ^2.4.0
  interval_time_picker: ^2.0.0+5
  jwt_decoder: ^2.0.1

  # MAP
  yandex_mapkit: ^3.2.0
  geolocator: ^9.0.2
  firebase_core: ^2.10.0
  firebase_messaging: ^14.4.1
  firebase_analytics: ^10.2.1
  firebase_crashlytics: ^3.1.1
  firebase_in_app_messaging: ^0.7.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  retrofit_generator: ^6.0.0+2
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1


flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
